# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\PreFramePropertiesWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_PreFrameProperties(object):
    def setupUi(self, Form_PreFrameProperties):
        Form_PreFrameProperties.setObjectName("Form_PreFrameProperties")
        Form_PreFrameProperties.resize(534, 405)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form_PreFrameProperties)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_Title = QtWidgets.QLabel(Form_PreFrameProperties)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Title.setFont(font)
        self.label_Title.setObjectName("label_Title")
        self.verticalLayout_3.addWidget(self.label_Title)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_Node = QtWidgets.QLabel(Form_PreFrameProperties)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setItalic(True)
        self.label_Node.setFont(font)
        self.label_Node.setObjectName("label_Node")
        self.verticalLayout_2.addWidget(self.label_Node)
        self.label_Element = QtWidgets.QLabel(Form_PreFrameProperties)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_Element.setFont(font)
        self.label_Element.setObjectName("label_Element")
        self.verticalLayout_2.addWidget(self.label_Element)
        self.label_Support = QtWidgets.QLabel(Form_PreFrameProperties)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setItalic(True)
        self.label_Support.setFont(font)
        self.label_Support.setObjectName("label_Support")
        self.verticalLayout_2.addWidget(self.label_Support)
        self.label_Force = QtWidgets.QLabel(Form_PreFrameProperties)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setItalic(True)
        self.label_Force.setFont(font)
        self.label_Force.setObjectName("label_Force")
        self.verticalLayout_2.addWidget(self.label_Force)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.spinBox_NodeCount = QtWidgets.QSpinBox(Form_PreFrameProperties)
        self.spinBox_NodeCount.setObjectName("spinBox_NodeCount")
        self.verticalLayout.addWidget(self.spinBox_NodeCount)
        self.spinBox_ElementCount = QtWidgets.QSpinBox(Form_PreFrameProperties)
        self.spinBox_ElementCount.setObjectName("spinBox_ElementCount")
        self.verticalLayout.addWidget(self.spinBox_ElementCount)
        self.spinBox_SupportCount = QtWidgets.QSpinBox(Form_PreFrameProperties)
        self.spinBox_SupportCount.setObjectName("spinBox_SupportCount")
        self.verticalLayout.addWidget(self.spinBox_SupportCount)
        self.spinBox_NodalForceCount = QtWidgets.QSpinBox(Form_PreFrameProperties)
        self.spinBox_NodalForceCount.setObjectName("spinBox_NodalForceCount")
        self.verticalLayout.addWidget(self.spinBox_NodalForceCount)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.button_Submit = QtWidgets.QPushButton(Form_PreFrameProperties)
        self.button_Submit.setObjectName("button_Submit")
        self.verticalLayout_3.addWidget(self.button_Submit)

        self.retranslateUi(Form_PreFrameProperties)
        QtCore.QMetaObject.connectSlotsByName(Form_PreFrameProperties)

    def retranslateUi(self, Form_PreFrameProperties):
        _translate = QtCore.QCoreApplication.translate
        Form_PreFrameProperties.setWindowTitle(_translate("Form_PreFrameProperties", "Form"))
        self.label_Title.setText(_translate("Form_PreFrameProperties", "Enter the primary frame properties in your modal:"))
        self.label_Node.setText(_translate("Form_PreFrameProperties", "Node Count: "))
        self.label_Element.setText(_translate("Form_PreFrameProperties", "Element Count:"))
        self.label_Support.setText(_translate("Form_PreFrameProperties", "How many support reactions in the frame?"))
        self.label_Force.setText(_translate("Form_PreFrameProperties", "How many nodal forces in the frame?"))
        self.button_Submit.setText(_translate("Form_PreFrameProperties", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_PreFrameProperties = QtWidgets.QWidget()
    ui = Ui_Form_PreFrameProperties()
    ui.setupUi(Form_PreFrameProperties)
    Form_PreFrameProperties.show()
    sys.exit(app.exec_())
